In [146]:
import numpy as np
import pandas as pd

In [147]:
df_socioec = pd.read_csv('dataset_olimpiadi_indicatori_ita.csv')
df_countries = pd.read_csv('Olympic_Country_Profiles.csv')
pop_wb = pd.read_csv('API_SP.POP.TOTL_DS2_EN_csv_v2_3107.csv', skiprows=4)

In [148]:
df_socioec['Anno'] = df_socioec[('Anno')].astype(int)
df_socioec

,Edizione_Olimpiadi,ID_Edizione,Anno,Nazione,Codice_NOC,Medaglie_Oro,Medaglie_Argento,Medaglie_Bronzo,Totale_Medaglie,Paese_Ospitante,...,RNL_Pro_Capite_USD,Iscrizioni_Scuola_Primaria_perc,Tasso_Mortalita_Neonatale,Tasso_Mortalita_Infantile,Aspettativa_di_Vita,Popolazione_Eta_Lavorativa_perc,Crescita_Demografica_perc,Popolazione_Totale,Popolazione_Urbana,Tasso_Urbanizzazione_perc
0,1964 Summer Olympics,16.0,1964,United States,USA,36.0,26.0,28.0,90.0,JPN,...,3325.0,NaN,NaN,25.200,70.019512,59.769954,1.544964,1.850355e+08,1.308124e+08,70.686700
1,1964 Summer Olympics,16.0,1964,Soviet Union,RUS,30.0,31.0,35.0,96.0,JPN,...,NaN,NaN,NaN,32.975,67.820573,63.134321,1.110863,1.219210e+08,6.767589e+07,55.495898
2,1964 Summer Olympics,16.0,1964,Japan,JPN,16.0,5.0,8.0,29.0,JPN,...,695.0,NaN,NaN,26.700,68.598720,65.650277,0.946220,9.452600e+07,6.119483e+07,64.727269
3,1964 Summer Olympics,16.0,1964,Germany,GER,10.0,22.0,18.0,50.0,JPN,...,1425.0,NaN,NaN,NaN,69.605561,66.372495,0.858387,7.373317e+07,5.636501e+07,76.439154
4,1964 Summer Olympics,16.0,1964,Italy,ITA,10.0,10.0,7.0,27.0,JPN,...,1060.0,NaN,23.325,41.700,69.320488,65.477136,0.691520,5.071688e+07,3.046761e+07,60.069421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3363,2020 Summer Olympics,61.0,2020,"Iran, Islamic Republic of",IRN,0.0,0.0,0.0,0.0,JPN,...,5317.5,105.547544,9.100,12.800,76.506750,69.484625,1.306438,8.550216e+07,6.376662e+07,74.572028
3364,2020 Summer Olympics,61.0,2020,"Netherlands, Kingdom of the",NLD,0.0,0.0,0.0,0.0,JPN,...,49475.0,104.964952,2.600,3.500,81.811585,65.311345,0.590597,1.718453e+07,1.581978e+07,92.049586
3365,2020 Summer Olympics,61.0,2020,"Korea, Democratic People's Republic of",PRK,0.0,0.0,0.0,0.0,JPN,...,NaN,92.064842,10.150,15.250,72.988250,69.770014,0.447847,2.587120e+07,1.602924e+07,61.956394
3366,2020 Summer Olympics,61.0,2020,"Palestine, State of",PSE,0.0,0.0,0.0,0.0,JPN,...,4055.0,96.563815,10.600,14.375,75.331000,56.914064,2.319896,4.519072e+06,3.864753e+06,85.516174
3367,2020 Summer Olympics,61.0,2020,"Tanzania, United Republic of",TZA,0.0,0.0,0.0,0.0,JPN,...,995.0,91.876625,23.125,36.800,65.215500,53.139620,3.221264,5.652223e+07,1.841442e+07,32.558175

In [149]:
df_socioec['Nazione'].unique()

array(['United States', 'Soviet Union', 'Japan', 'Germany', 'Italy',
       'Hungary', 'Poland', 'Australia', 'Czechoslovakia',
       'Great Britain', 'Bulgaria', 'Finland', 'New Zealand', 'Romania',
       'Netherlands', 'Türkiye', 'Sweden', 'Denmark', 'Yugoslavia',
       'Belgium', 'France', 'Canada', 'Switzerland', 'Ethiopia', 'India',
       'The Bahamas', 'Republic of Korea', 'Trinidad and Tobago',
       'Tunisia', 'Argentina', 'Cuba', 'Pakistan', 'Philippines',
       'Islamic Republic of Iran', 'Brazil', 'Ghana', 'Ireland', 'Kenya',
       'Mexico', 'Nigeria', 'Uruguay', 'East Germany', 'West Germany',
       'Norway', 'Venezuela', 'Austria', 'Mongolia', 'Uganda', 'Cameroon',
       'Jamaica', 'Chinese Taipei', 'Greece',
       "Democratic People's Republic of Korea", 'Colombia', 'Lebanon',
       'Niger', 'Spain', 'Portugal', 'Bermuda', 'Puerto Rico', 'Thailand',
       'Zimbabwe', 'United Republic of Tanzania', 'Guyana',
       "People's Republic of China", 'Morocco', "Côte d'Ivoire", 'Egypt',
       'Peru', 'Syrian Arab Republic', 'Algeria', 'Dominican Republic',
       'Iceland', 'Zambia', 'Suriname', 'Chile', 'Costa Rica',
       'Indonesia', 'Netherlands Antilles', 'Senegal',
       'United States Virgin Islands', 'Djibouti', 'Unified Team',
       'Estonia', 'Lithuania', 'Latvia', 'Namibia', 'South Africa',
       'Croatia', 'Independent Olympic Athletes', 'Israel', 'Slovenia',
       'Malaysia', 'Qatar', 'Russian Federation', 'Ukraine', 'Czechia',
       'Kazakhstan', 'Belarus', 'Serbia and Montenegro', 'Slovakia',
       'Armenia', 'Burundi', 'Ecuador', 'Republic of Moldova',
       'Uzbekistan', 'Azerbaijan', 'Tonga', 'Georgia', 'Mozambique',
       'Kingdom of Saudi Arabia', 'Sri Lanka', 'Vietnam', 'Barbados',
       'Kuwait', 'Kyrgyzstan', 'North Macedonia', 'United Arab Emirates',
       'Paraguay', 'Eritrea', 'Panama', 'Serbia', 'Tajikistan', 'Samoa',
       'Singapore', 'Sudan', 'Afghanistan', 'Mauritius', 'Togo',
       'Bahrain', 'Grenada', 'Botswana', 'Cyprus', 'Gabon', 'Guatemala',
       'Montenegro', 'Fiji', 'Jordan', 'Kosovo', 'ROC', 'San Marino',
       'Turkmenistan', 'Burkina Faso', 'Aruba', 'Angola', 'Albania',
       'Andorra', 'American Samoa', 'Antigua and Barbuda', 'Benin',
       'Bangladesh', 'Bahamas', 'Bosnia and Herzegovina', 'Belize',
       'Brunei Darussalam', 'Bhutan', 'Central African Republic', 'China',
       'Congo', 'Comoros', 'Cabo Verde', 'Cayman Islands', 'Dominica',
       'Guinea', 'Gambia', 'Guinea-Bissau', 'Equatorial Guinea',
       'Greenland', 'Guam', 'Hong Kong', 'Honduras', 'Haiti', 'Iraq',
       'Cambodia', 'Kiribati', 'Saint Kitts and Nevis',
       "Lao People's Democratic Republic", 'Liberia', 'Libya',
       'Saint Lucia', 'Liechtenstein', 'Lesotho', 'Luxembourg', 'Macao',
       'Monaco', 'Madagascar', 'Maldives', 'Marshall Islands', 'Mali',
       'Malta', 'Myanmar', 'Mauritania', 'Malawi', 'New Caledonia',
       'Nicaragua', 'Nepal', 'Nauru', 'Oman', 'Palau', 'Papua New Guinea',
       'French Polynesia', 'Rwanda', 'Saudi Arabia', 'Solomon Islands',
       'Sierra Leone', 'El Salvador', 'Somalia', 'South Sudan',
       'Sao Tome and Principe', 'Eswatini', 'Seychelles', 'Chad',
       'Timor-Leste', 'Tuvalu', 'Saint Vincent and the Grenadines',
       'Virgin Islands (U.S.)', 'Viet Nam', 'Vanuatu', 'Yemen',
       'United States of America', 'Hong Kong, China',
       'Bolivia, Plurinational State of',
       'Congo, Democratic Republic of the',
       'Micronesia, Federated States of', 'Iran, Islamic Republic of',
       'Moldova, Republic of', 'Netherlands, Kingdom of the',
       "Korea, Democratic People's Republic of", 'Palestine, State of',
       'Tanzania, United Republic of',
       'Venezuela, Bolivarian Republic of', 'Korea, Republic of'],
      dtype=object)

In [150]:
mapping_varianti = {
    'Iran, Islamic Republic of': 'Iran',
    'Islamic Republic of Iran': 'Iran',
    'Tanzania, United Republic of': 'Tanzania',
    'United Republic of Tanzania': 'Tanzania',
    'Moldova, Republic of': 'Moldova',
    'Republic of Moldova': 'Moldova',
    'Venezuela, Bolivarian Republic of': 'Venezuela',
    'Viet Nam': 'Vietnam',
    'Congo, Democratic Republic of the': 'Democratic Republic of the Congo',
    'The Bahamas': 'Bahamas',
    'Korea, Republic of': 'South Korea',
    'Republic of Korea': 'South Korea',
    "Korea, Democratic People's Republic of": 'North Korea',
    "Democratic People's Republic of Korea": 'North Korea',
    "People's Republic of China": 'China',
    'Hong Kong, China': 'Hong Kong',
    'United States of America': 'United States',
    'Kingdom of Saudi Arabia': 'Saudi Arabia',
    'Palestine, State of': 'Palestine',
    'Virgin Islands (U.S.)': 'United States Virgin Islands',
    'United States Virgin Islands': 'United States Virgin Islands',
    'Micronesia, Federated States of': 'Federated States of Micronesia',
    'Bolivia, Plurinational State of': 'Bolivia',
    'Netherlands, Kingdom of the': 'Netherlands',
    'Guinea Bissau': 'Guinea-Bissau',
    'The Gambia': 'Gambia',
    'São Tomé and Príncipe': 'Sao Tome and Principe'
}

In [151]:
country_mapping = {
    **mapping_varianti
}

In [152]:

df_socioec['Nazione'] = df_socioec['Nazione'].replace(country_mapping)

In [153]:
df_countries['country'] = df_countries['country'].replace(country_mapping)

In [154]:
noc_to_country = df_socioec.groupby('Codice_NOC')['Nazione'].unique()
noc_multi_country = noc_to_country[noc_to_country.apply(len) > 1]
noc_multi_country

Codice_NOC
BRN          [Bahrain, Brunei Darussalam]
RUS    [Soviet Union, Russian Federation]
Name: Nazione, dtype: object

In [155]:
df_socioec.loc[df_socioec['Nazione'] == 'Brunei Darussalam', 'Codice_NOC'] = 'BRU'
df_socioec.loc[df_socioec['Nazione'] == 'Soviet Union', 'Codice_NOC'] = 'URS'

In [156]:
noc_to_country = df_socioec.groupby('Codice_NOC')['Nazione'].unique()
noc_multi_country = noc_to_country[noc_to_country.apply(len) > 1]
noc_multi_country

Series([], Name: Nazione, dtype: object)

In [157]:
df_socioec['Nazione'].unique()

array(['United States', 'Soviet Union', 'Japan', 'Germany', 'Italy',
       'Hungary', 'Poland', 'Australia', 'Czechoslovakia',
       'Great Britain', 'Bulgaria', 'Finland', 'New Zealand', 'Romania',
       'Netherlands', 'Türkiye', 'Sweden', 'Denmark', 'Yugoslavia',
       'Belgium', 'France', 'Canada', 'Switzerland', 'Ethiopia', 'India',
       'Bahamas', 'South Korea', 'Trinidad and Tobago', 'Tunisia',
       'Argentina', 'Cuba', 'Pakistan', 'Philippines', 'Iran', 'Brazil',
       'Ghana', 'Ireland', 'Kenya', 'Mexico', 'Nigeria', 'Uruguay',
       'East Germany', 'West Germany', 'Norway', 'Venezuela', 'Austria',
       'Mongolia', 'Uganda', 'Cameroon', 'Jamaica', 'Chinese Taipei',
       'Greece', 'North Korea', 'Colombia', 'Lebanon', 'Niger', 'Spain',
       'Portugal', 'Bermuda', 'Puerto Rico', 'Thailand', 'Zimbabwe',
       'Tanzania', 'Guyana', 'China', 'Morocco', "Côte d'Ivoire", 'Egypt',
       'Peru', 'Syrian Arab Republic', 'Algeria', 'Dominican Republic',
       'Iceland', 'Zambia', 'Suriname', 'Chile', 'Costa Rica',
       'Indonesia', 'Netherlands Antilles', 'Senegal',
       'United States Virgin Islands', 'Djibouti', 'Unified Team',
       'Estonia', 'Lithuania', 'Latvia', 'Namibia', 'South Africa',
       'Croatia', 'Independent Olympic Athletes', 'Israel', 'Slovenia',
       'Malaysia', 'Qatar', 'Russian Federation', 'Ukraine', 'Czechia',
       'Kazakhstan', 'Belarus', 'Serbia and Montenegro', 'Slovakia',
       'Armenia', 'Burundi', 'Ecuador', 'Moldova', 'Uzbekistan',
       'Azerbaijan', 'Tonga', 'Georgia', 'Mozambique', 'Saudi Arabia',
       'Sri Lanka', 'Vietnam', 'Barbados', 'Kuwait', 'Kyrgyzstan',
       'North Macedonia', 'United Arab Emirates', 'Paraguay', 'Eritrea',
       'Panama', 'Serbia', 'Tajikistan', 'Samoa', 'Singapore', 'Sudan',
       'Afghanistan', 'Mauritius', 'Togo', 'Bahrain', 'Grenada',
       'Botswana', 'Cyprus', 'Gabon', 'Guatemala', 'Montenegro', 'Fiji',
       'Jordan', 'Kosovo', 'ROC', 'San Marino', 'Turkmenistan',
       'Burkina Faso', 'Aruba', 'Angola', 'Albania', 'Andorra',
       'American Samoa', 'Antigua and Barbuda', 'Benin', 'Bangladesh',
       'Bosnia and Herzegovina', 'Belize', 'Brunei Darussalam', 'Bhutan',
       'Central African Republic', 'Congo', 'Comoros', 'Cabo Verde',
       'Cayman Islands', 'Dominica', 'Guinea', 'Gambia', 'Guinea-Bissau',
       'Equatorial Guinea', 'Greenland', 'Guam', 'Hong Kong', 'Honduras',
       'Haiti', 'Iraq', 'Cambodia', 'Kiribati', 'Saint Kitts and Nevis',
       "Lao People's Democratic Republic", 'Liberia', 'Libya',
       'Saint Lucia', 'Liechtenstein', 'Lesotho', 'Luxembourg', 'Macao',
       'Monaco', 'Madagascar', 'Maldives', 'Marshall Islands', 'Mali',
       'Malta', 'Myanmar', 'Mauritania', 'Malawi', 'New Caledonia',
       'Nicaragua', 'Nepal', 'Nauru', 'Oman', 'Palau', 'Papua New Guinea',
       'French Polynesia', 'Rwanda', 'Solomon Islands', 'Sierra Leone',
       'El Salvador', 'Somalia', 'South Sudan', 'Sao Tome and Principe',
       'Eswatini', 'Seychelles', 'Chad', 'Timor-Leste', 'Tuvalu',
       'Saint Vincent and the Grenadines', 'Vanuatu', 'Yemen', 'Bolivia',
       'Democratic Republic of the Congo',
       'Federated States of Micronesia', 'Palestine'], dtype=object)

In [158]:
paesi_socioec = set(df_socioec['Nazione'].unique())
paesi_countries = set(df_countries['country'].unique())

In [159]:
solo_in_socioec = paesi_socioec - paesi_countries
print("Solo in df_socioec:", solo_in_socioec)

solo_in_countries = paesi_countries - paesi_socioec
print("Solo in df_countries:", solo_in_countries)

Solo in df_socioec: {'French Polynesia', 'Greenland', 'Macao', 'New Caledonia'}
Solo in df_countries: {'South Vietnam', 'Russian Olympic Committee', 'Individual Neutral Athletes', 'North Yemen', 'Newfoundland', 'Bohemia', 'South Yemen', 'United Arab Republic', 'Mixed team', 'Australasia', 'Refugee Olympic Team', 'West Indies Federation', 'Crete', 'Cook Islands', 'Unknown', 'Saar', 'British Virgin Islands', 'North Borneo', 'Rhodesia', 'Korea Team', 'Malaya'}

In [160]:
paesi_comuni = paesi_socioec & paesi_countries

noc_socioec = (
    df_socioec[df_socioec['Nazione'].isin(paesi_comuni)]
    .groupby('Nazione')['Codice_NOC']
    .unique()
)

noc_countries = (
    df_countries[df_countries['country'].isin(paesi_comuni)]
    .groupby('country')['noc']
    .unique()
)

confronto_noc = pd.concat([noc_socioec, noc_countries], axis=1, keys=['noc_socioec', 'noc_countries'])
confronto_noc

               noc_socioec noc_countries
Afghanistan          [AFG]         [AFG]
Albania              [ALB]         [ALB]
Algeria         [ALG, DZA]         [ALG]
American Samoa       [ASM]         [ASA]
Andorra              [AND]         [AND]
...                    ...           ...
West Germany         [FRG]         [FRG]
Yemen                [YEM]         [YEM]
Yugoslavia           [YUG]         [YUG]
Zambia               [ZAM]         [ZAM]
Zimbabwe             [ZIM]         [ZIM]

[214 rows x 2 columns]

In [161]:
confronto_noc.to_csv("codici.csv", index=False)

In [162]:
df_socioec['Codice_NOC'] = df_socioec.groupby('Nazione')['Codice_NOC'].transform('first')

In [163]:
paesi_socioec2  = set(df_socioec['Nazione'].unique())
paesi_countries2 = set(df_countries['country'].unique())

In [164]:
paesi_comuni2 = paesi_socioec2 & paesi_countries2

noc_socioec = (
    df_socioec[df_socioec['Nazione'].isin(paesi_comuni2)]
    .groupby('Nazione')['Codice_NOC']
    .unique()
)

noc_countries = (
    df_countries[df_countries['country'].isin(paesi_comuni2)]
    .groupby('country')['noc']
    .unique()
)

confronto_noc2 = pd.concat([noc_socioec, noc_countries], axis=1, keys=['noc_socioec', 'noc_countries'])
confronto_noc2

               noc_socioec noc_countries
Afghanistan          [AFG]         [AFG]
Albania              [ALB]         [ALB]
Algeria              [ALG]         [ALG]
American Samoa       [ASM]         [ASA]
Andorra              [AND]         [AND]
...                    ...           ...
West Germany         [FRG]         [FRG]
Yemen                [YEM]         [YEM]
Yugoslavia           [YUG]         [YUG]
Zambia               [ZAM]         [ZAM]
Zimbabwe             [ZIM]         [ZIM]

[214 rows x 2 columns]

In [165]:
confronto_noc2.to_csv('codici2.csv', index=False)

In [166]:
year_cols = [c for c in pop_wb.columns if c.isdigit()]

pop_long = pop_wb.melt(
    id_vars=['Country Code',  'Country Name'],
    value_vars=year_cols,
    var_name='year',
    value_name='population_wb'
)
pop_long['year'] = pop_long['year'].astype(int)
pop_long['population_wb'] = pd.to_numeric(pop_long['population_wb'], errors='coerce')

In [167]:
pop_long

      Country Code                 Country Name  year  population_wb
0              ABW                        Aruba  1960        54922.0
1              AFE  Africa Eastern and Southern  1960    130075728.0
2              AFG                  Afghanistan  1960      9035043.0
3              AFW   Africa Western and Central  1960     97630925.0
4              AGO                       Angola  1960      5231654.0
...            ...                          ...   ...            ...
17485          XKX                       Kosovo  2025      1576876.0
17486          YEM                  Yemen, Rep.  2025     41773878.0
17487          ZAF                 South Africa  2025     64747319.0
17488          ZMB                       Zambia  2025     21913874.0
17489          ZWE                     Zimbabwe  2025     16950795.0

[17490 rows x 4 columns]

In [168]:
pop_long['Country Name'] = pop_long['Country Name'].replace(country_mapping)

In [169]:
paesi_socioec3  = set(df_socioec['Nazione'].unique())
paesi_pop3 = set(pop_long['Country Name'].unique())

In [170]:
solo_in_socioec3 = paesi_socioec3 - paesi_pop3
print("Solo in df_socioec:", solo_in_socioec3)

solo_in_pop3 = paesi_pop3 - paesi_socioec3
print("Solo in df_countries:", solo_in_pop3)

Solo in df_socioec: {'Saint Lucia', 'Saint Kitts and Nevis', 'Kyrgyzstan', 'Serbia and Montenegro', 'Soviet Union', 'Great Britain', 'North Korea', 'Saint Vincent and the Grenadines', 'West Germany', 'Democratic Republic of the Congo', 'Iran', 'Yugoslavia', 'East Germany', 'South Korea', 'Bahamas', 'Independent Olympic Athletes', 'Yemen', 'Federated States of Micronesia', 'Congo', 'Gambia', 'Macao', 'Czechoslovakia', 'Türkiye', 'Chinese Taipei', 'Slovakia', 'Palestine', 'Venezuela', "Lao People's Democratic Republic", 'Somalia', 'Egypt', 'Netherlands Antilles', "Côte d'Ivoire", 'ROC', 'Puerto Rico', 'Hong Kong', 'Unified Team'}
Solo in df_countries: {'IDA blend', 'Congo, Rep.', 'OECD members', 'Venezuela, RB', 'High income', 'St. Lucia', 'Euro area', 'Egypt, Arab Rep.', 'St. Martin (French part)', 'Small states', 'Turks and Caicos Islands', 'Central Europe and the Baltics', 'Early-demographic dividend', 'Macao SAR, China', 'Latin America & Caribbean (excluding high income)', 'United Kingdom', 'East Asia & Pacific (IDA & IBRD countries)', 'British Virgin Islands', 'Lower middle income', 'Bahamas, The', 'IDA & IBRD total', 'Micronesia, Fed. Sts.', 'IBRD only', 'Congo, Dem. Rep.', 'Yemen, Rep.', 'Heavily indebted poor countries (HIPC)', 'Middle income', 'Iran, Islamic Rep.', 'Channel Islands', 'Kyrgyz Republic', 'South Asia (IDA & IBRD)', "Cote d'Ivoire", 'Other small states', 'World', 'Africa Western and Central', 'Upper middle income', 'Latin America & Caribbean', 'Europe & Central Asia (excluding high income)', 'European Union', 'Turkiye', 'Somalia, Fed. Rep.', 'Middle East, North Africa, Afghanistan & Pakistan', 'Slovak Republic', 'Sint Maarten (Dutch part)', 'Gibraltar', 'Isle of Man', 'Korea, Rep.', 'Not classified', 'Puerto Rico (US)', "Korea, Dem. People's Rep.", 'Low & middle income', 'Post-demographic dividend', 'Africa Eastern and Southern', 'Late-demographic dividend', 'Lao PDR', 'Pacific island small states', 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)', 'IDA total', 'Sub-Saharan Africa', 'Gambia, The', 'St. Kitts and Nevis', 'St. Vincent and the Grenadines', 'Low income', 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)', 'Hong Kong SAR, China', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Northern Mariana Islands', 'IDA only', 'Pre-demographic dividend', 'East Asia & Pacific', 'East Asia & Pacific (excluding high income)', 'Curacao', 'Europe & Central Asia', 'West Bank and Gaza', 'South Asia', 'Least developed countries: UN classification', 'Caribbean small states', 'Arab World', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Europe & Central Asia (IDA & IBRD countries)', 'Sub-Saharan Africa (excluding high income)', 'Faroe Islands', 'North America'}

In [171]:
mapping_varianti2 = {
    'Egypt, Arab Rep.': 'Egypt',
    'Lao PDR': "Lao People's Democratic Republic",
    'Gambia, The': 'Gambia',
    'Turkiye': 'Türkiye',
    'United Kingdom': 'Great Britain',
    "Korea, Dem. People's Rep.": 'North Korea',
    'Korea, Rep.': 'South Korea',
    'Bahamas, The': 'Bahamas',
    'Somalia, Fed. Rep.': 'Somalia',
    'Congo, Dem. Rep.': 'Democratic Republic of the Congo',
    'Hong Kong SAR, China': 'Hong Kong',
    'Iran, Islamic Rep.': 'Iran',
    'Congo, Rep.': 'Congo',
    'Slovak Republic': 'Slovakia',
    'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'St. Lucia': 'Saint Lucia',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Venezuela, RB': 'Venezuela',
    "Cote d'Ivoire": "Côte d'Ivoire",
    'Puerto Rico (US)': 'Puerto Rico',
    'Macao SAR, China': 'Macao',
    'St. Kitts and Nevis': 'Saint Kitts and Nevis',
    'Yemen, Rep.': 'Yemen',
    'Micronesia, Fed. Sts.': 'Federated States of Micronesia',
}

In [172]:
country_mapping2 = {
    **mapping_varianti2
}

In [173]:
pop_long['Country Name'] = pop_long['Country Name'].replace(country_mapping2)

In [174]:
paesi_socioec4 = set(df_socioec['Nazione'].unique())
paesi_pop4 = set(pop_long['Country Name'].unique())

In [175]:
solo_in_socioec4 = paesi_socioec4 - paesi_pop4
print("Solo in df_socioec:", solo_in_socioec4)

solo_in_pop4 = paesi_pop4 - paesi_socioec4
print("Solo in df_countries:", solo_in_pop4)

Solo in df_socioec: {'Independent Olympic Athletes', 'Netherlands Antilles', 'Yugoslavia', 'Soviet Union', 'ROC', 'East Germany', 'Czechoslovakia', 'Serbia and Montenegro', 'Chinese Taipei', 'Unified Team', 'West Germany', 'Palestine'}
Solo in df_countries: {'Latin America & Caribbean', 'Europe & Central Asia (excluding high income)', 'IDA blend', 'IDA & IBRD total', 'European Union', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Middle East, North Africa, Afghanistan & Pakistan', 'IBRD only', 'Northern Mariana Islands', 'OECD members', 'Sint Maarten (Dutch part)', 'IDA only', 'High income', 'Pre-demographic dividend', 'Euro area', 'Gibraltar', 'Isle of Man', 'Heavily indebted poor countries (HIPC)', 'East Asia & Pacific', 'Not classified', 'Middle income', 'East Asia & Pacific (excluding high income)', 'St. Martin (French part)', 'Curacao', 'Low & middle income', 'Small states', 'Europe & Central Asia', 'Post-demographic dividend', 'Turks and Caicos Islands', 'West Bank and Gaza', 'South Asia', 'Central Europe and the Baltics', 'Early-demographic dividend', 'Channel Islands', 'South Asia (IDA & IBRD)', 'Africa Eastern and Southern', 'Late-demographic dividend', 'Pacific island small states', 'Least developed countries: UN classification', 'Caribbean small states', 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)', 'Latin America & Caribbean (excluding high income)', 'Low income', 'Arab World', 'Other small states', 'IDA total', 'East Asia & Pacific (IDA & IBRD countries)', 'Sub-Saharan Africa (IDA & IBRD countries)', 'World', 'Europe & Central Asia (IDA & IBRD countries)', 'Sub-Saharan Africa', 'Africa Western and Central', 'British Virgin Islands', 'Sub-Saharan Africa (excluding high income)', 'Faroe Islands', 'Lower middle income', 'North America', 'Upper middle income', 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)'}

In [176]:
paesi_comuni4 = paesi_socioec4 & paesi_pop4

noc_socioec = (
    df_socioec[df_socioec['Nazione'].isin(paesi_comuni4)]
    .groupby('Nazione')['Codice_NOC']
    .unique()
)

noc_pop = (
   pop_long[pop_long['Country Name'].isin(paesi_comuni4)]
    .groupby('Country Name')['Country Code']
    .unique()
)

confronto_noc4 = pd.concat([noc_socioec, noc_pop], axis=1, keys=['noc_socioec', 'noc_pop'])
confronto_noc4

               noc_socioec noc_pop
Afghanistan          [AFG]   [AFG]
Albania              [ALB]   [ALB]
Algeria              [ALG]   [DZA]
American Samoa       [ASM]   [ASM]
Andorra              [AND]   [AND]
...                    ...     ...
Venezuela            [VEN]   [VEN]
Vietnam              [VIE]   [VNM]
Yemen                [YEM]   [YEM]
Zambia               [ZAM]   [ZMB]
Zimbabwe             [ZIM]   [ZWE]

[206 rows x 2 columns]

In [177]:
pop_long.groupby('Country Name')['Country Code'].nunique().sort_values(ascending=False).head()

Country Name
Afghanistan                    1
Africa Eastern and Southern    1
Africa Western and Central     1
Albania                        1
Algeria                        1
Name: Country Code, dtype: int64

In [178]:
def get_population_for_olympic_year(country_name, olympic_year, pop_data, years_back=4):
    target_years = list(range(olympic_year - years_back, olympic_year))
    subset = pop_data[
        (pop_data['Country Name'] == country_name) &
        (pop_data['year'].isin(target_years))
    ]['population_wb']
    if subset.dropna().empty:
        return np.nan
    return subset.mean(skipna=True)


nan_mask = df_socioec['Popolazione_Totale'].isna()

df_socioec.loc[nan_mask, 'Popolazione_Totale'] = df_socioec[nan_mask].apply(
    lambda row: get_population_for_olympic_year(
        country_name=row['Nazione'],
        olympic_year=int(row['Anno']),
        pop_data=pop_long
    ),
    axis=1
)

In [179]:
df_socioec[df_socioec['Popolazione_Totale'].isna()].groupby('Nazione').size().sort_values(ascending=False)

Nazione
Chinese Taipei                  10
Czechoslovakia                   7
Palestine                        7
Yugoslavia                       7
East Germany                     5
West Germany                     5
Serbia and Montenegro            3
Independent Olympic Athletes     2
Netherlands Antilles             1
ROC                              1
Unified Team                     1
dtype: int64

In [180]:
duplicati = df_socioec[df_socioec.duplicated(keep=False)]
print(f"Righe duplicate: {len(duplicati)}")
duplicati

Righe duplicate: 0

Empty DataFrame
Columns: [Edizione_Olimpiadi, ID_Edizione, Anno, Nazione, Codice_NOC, Medaglie_Oro, Medaglie_Argento, Medaglie_Bronzo, Totale_Medaglie, Paese_Ospitante, Citta_Ospitante, Precipitazioni_Medie_mm, Superficie_Totale_km2, Investimenti_Diretti_Esteri_perc_PIL, Densita_Popolazione, Inflazione_Prezzi_Consumo, Spesa_Militare_Valuta_Locale, Spesa_Militare_perc_PIL, Spesa_Pubblica_Consumi_USD, Spesa_Nazionale_Lorda_Valuta_Locale, Interscambio_Commerciale_perc_PIL, Valore_Aggiunto_Industria_perc_PIL, Valore_Aggiunto_Servizi_Valuta_Locale, Valore_Aggiunto_Servizi_perc_PIL, Inflazione_Deflatore_PIL, PIL_Assoluto_USD, PIL_Valuta_Locale, Crescita_PIL_perc_annua, PIL_Pro_Capite_USD, RNL_Valuta_Locale, RNL_Pro_Capite_USD, Iscrizioni_Scuola_Primaria_perc, Tasso_Mortalita_Neonatale, Tasso_Mortalita_Infantile, Aspettativa_di_Vita, Popolazione_Eta_Lavorativa_perc, Crescita_Demografica_perc, Popolazione_Totale, Popolazione_Urbana, Tasso_Urbanizzazione_perc]
Index: []

[0 rows x 40 columns]

In [181]:
df_socioec.to_csv("dataset_indicatori_definitivo.csv", index=False)